### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by jn1512** [npr/pmp-issues#64]
Hello,

The content from "The World" that we pull from PMP into our Core Publisher site is having trouble with the images.

You can see an example of this at:
http://wvxu.org/programs/world

Thanks!

**Comment by JNemic** [comment]
Hello! Thanks for reporting this. We're aware of the issue and have been working with DS to resolve. I'll let you know an ETA on a fix as soon as we know.

**Comment by kookster** [comment]
I have a case where the image was updated after the doc was published to the PMP (Sound Opinions updated the image on their Holiday Spectacular episode), and CP has not updated to show the new image:

http://capeandislands.org/post/sound-opinions-holiday-spectacular-hillbilly-christmas

http://nashvillepublicradio.org/post/sound-opinions-holiday-spectacular-hillbilly-christmas#stream/0

Is this fixed in CP, is there a way to get this doc corrected at least? @scottsmith130

**Comment by scottsmith130** [comment]
@kookster sorry for the late reply here, I had this forwarded to the team at DS to take a look at

**Comment by kookster** [comment]
Thanks @scottsmith130 - is someone working on it? They are still broken.

**Comment by scottsmith130** [comment]
Yes, the Core Publisher team is still addressing it.

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4094
